# Generated by Django 6.0.2 on 2026-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_college_profile_course_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reference_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reference_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reference_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
