# Generated by Django 6.0.2 on 2026-03-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loan_reminder_sent_profile_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='total_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
