# Generated by Django 6.0.2 on 2026-03-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_fund_total_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
