# Generated by Django 6.0.2 on 2026-03-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_application_priority_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='repayment_plan',
            field=models.CharField(choices=[('30', '30 Days'), ('60', '60 Days'), ('90', '90 Days')], default=30, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
