# Generated by Django 4.2.17 on 2026-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_application_phone_application_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_risk_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
